/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fs/open-output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Output Folder */
        post: operations["open_output_folder_fs_open_output_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fs/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal File */
        post: operations["reveal_file_fs_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History */
        get: operations["list_history_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete History */
        delete: operations["delete_history_history__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Batch Job */
        post: operations["create_batch_job_jobs_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Output */
        get: operations["download_output_jobs_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/ingest-paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Local Paths */
        post: operations["ingest_local_paths_jobs_ingest_paths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/single": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Single */
        post: operations["process_single_jobs_single_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Files */
        post: operations["upload_files_jobs_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Status */
        get: operations["get_job_status_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Job Zip */
        get: operations["download_job_zip_jobs__job_id__zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/benchmark/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Model Benchmark */
        post: operations["run_model_benchmark_models_benchmark_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/benchmark/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Benchmark Status */
        get: operations["get_model_benchmark_status_models_benchmark_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Model Catalog */
        get: operations["list_model_catalog_models_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Storage Config */
        get: operations["get_model_storage_config_models_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Model Storage Config */
        patch: operations["update_model_storage_config_models_config_patch"];
        trace?: never;
    };
    "/models/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Model Catalog */
        post: operations["refresh_model_catalog_models_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Model */
        delete: operations["delete_model_models__model_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install Model */
        post: operations["install_model_models__model_id__install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Status */
        get: operations["get_model_status_models__model_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_presets_get"];
        put?: never;
        /** Create Preset */
        post: operations["create_preset_presets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{preset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Preset */
        delete: operations["delete_preset_presets__preset_id__delete"];
        options?: never;
        head?: never;
        /** Update Preset */
        patch: operations["update_preset_presets__preset_id__patch"];
        trace?: never;
    };
    "/providers/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider Settings */
        get: operations["get_provider_settings_providers_settings_get"];
        put?: never;
        /** Save Provider Settings */
        post: operations["save_provider_settings_providers_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider Status */
        get: operations["get_provider_status_providers_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/test/{provider_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Provider */
        post: operations["test_provider_providers_test__provider_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watch-folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watch Folders */
        get: operations["list_watch_folders_watch_folders_get"];
        put?: never;
        /** Create Watch Folder */
        post: operations["create_watch_folder_watch_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watch-folders/{watch_folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watch Folder */
        delete: operations["delete_watch_folder_watch_folders__watch_folder_id__delete"];
        options?: never;
        head?: never;
        /** Update Watch Folder */
        patch: operations["update_watch_folder_watch_folders__watch_folder_id__patch"];
        trace?: never;
    };
    "/watch-folders/{watch_folder_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Watch Folder */
        post: operations["disable_watch_folder_watch_folders__watch_folder_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watch-folders/{watch_folder_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Watch Folder */
        post: operations["enable_watch_folder_watch_folders__watch_folder_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watch-folders/{watch_folder_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watch Folder Status */
        get: operations["watch_folder_status_watch_folders__watch_folder_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_files_jobs_upload_post */
        Body_upload_files_jobs_upload_post: {
            /** Files */
            files: string[];
        };
        /** CreateBatchJobRequest */
        CreateBatchJobRequest: {
            /**
             * Items
             * @description Absolute or relative local file paths
             */
            items?: string[];
            options: components["schemas"]["ProcessingOptions"];
        };
        /** CreateJobRequest */
        CreateJobRequest: {
            /** Mask Hints */
            mask_hints?: {
                [key: string]: string;
            };
            options: components["schemas"]["ProcessingOptions"];
            /** Upload Ids */
            upload_ids?: string[];
        };
        /** CreatePresetRequest */
        CreatePresetRequest: {
            /** Name */
            name: string;
            options: components["schemas"]["ProcessingOptions"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** HistoryItem */
        HistoryItem: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Engine Used */
            engine_used: string;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: number;
            /** Input Path */
            input_path: string;
            /** Original Filename */
            original_filename: string;
            /** Output Filename */
            output_filename: string;
            /** Output Path */
            output_path: string;
            /** Processing Options */
            processing_options: string;
            /** Provider Used */
            provider_used: string;
            /** Success */
            success: boolean;
        };
        /** IngestPathsRequest */
        IngestPathsRequest: {
            /**
             * Paths
             * @description Absolute local file paths
             */
            paths?: string[];
        };
        /** JobFileResult */
        JobFileResult: {
            /** Engine Used */
            engine_used?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Input Path */
            input_path: string;
            /** Output Filename */
            output_filename?: string | null;
            /** Output Path */
            output_path?: string | null;
            /** Provider Used */
            provider_used?: string | null;
            /** Started At */
            started_at?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "processing" | "done" | "failed" | "canceled";
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Files */
            files?: components["schemas"]["JobFileResult"][];
            /** Job Id */
            job_id: string;
            options: components["schemas"]["ProcessingOptions"];
            /** Progress */
            progress: number;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "processing" | "done" | "failed" | "canceled";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ModelBenchmarkImageResult */
        ModelBenchmarkImageResult: {
            /** Alpha Ratio */
            alpha_ratio?: number | null;
            /** Alpha Std */
            alpha_std?: number | null;
            /** Bbox Ratio */
            bbox_ratio?: number | null;
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Image Name */
            image_name: string;
            /** Input Path */
            input_path: string;
            /** Output Path */
            output_path?: string | null;
            /**
             * Passed
             * @default false
             */
            passed: boolean;
        };
        /** ModelBenchmarkReport */
        ModelBenchmarkReport: {
            /** Benchmark Dir */
            benchmark_dir: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Log Path */
            log_path?: string | null;
            /** Results */
            results: components["schemas"]["ModelBenchmarkResult"][];
            /** Sample Dir */
            sample_dir: string;
            /**
             * Task
             * @enum {string}
             */
            task: "cutout" | "enhance" | "tagging" | "ocr";
            /** Total Images */
            total_images: number;
            /** Total Models */
            total_models: number;
        };
        /** ModelBenchmarkResult */
        ModelBenchmarkResult: {
            /** Average Alpha Ratio */
            average_alpha_ratio?: number | null;
            /** Average Alpha Std */
            average_alpha_std?: number | null;
            /** Average Bbox Ratio */
            average_bbox_ratio?: number | null;
            /** Average Elapsed Ms */
            average_elapsed_ms?: number | null;
            /**
             * Engine
             * @enum {string}
             */
            engine: "rembg" | "realesrgan" | "wdtagger" | "tesseract";
            /** Failed Images */
            failed_images: number;
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["ModelBenchmarkImageResult"][];
            /** Model Id */
            model_id: string;
            /** Model Name */
            model_name: string;
            /**
             * Notes
             * @default []
             */
            notes: string[];
            /** Output Dir */
            output_dir?: string | null;
            /** Passed Images */
            passed_images: number;
            /** Preview Path */
            preview_path?: string | null;
            /** Quality Preset */
            quality_preset?: string | null;
            /**
             * Runtime Config
             * @default {}
             */
            runtime_config: {
                [key: string]: boolean | number | string | null;
            };
            /** Score */
            score: number;
            /** Total Images */
            total_images: number;
        };
        /** ModelBenchmarkStatus */
        ModelBenchmarkStatus: {
            /** Benchmark Dir */
            benchmark_dir?: string | null;
            /**
             * Completed Images
             * @default 0
             */
            completed_images: number;
            /**
             * Completed Models
             * @default 0
             */
            completed_models: number;
            /** Current Image Name */
            current_image_name?: string | null;
            /** Current Model Id */
            current_model_id?: string | null;
            /** Current Model Name */
            current_model_name?: string | null;
            /** Current Model Started At */
            current_model_started_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /** Log Path */
            log_path?: string | null;
            report?: components["schemas"]["ModelBenchmarkReport"] | null;
            /** Sample Dir */
            sample_dir?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "idle" | "running" | "done" | "failed";
            /**
             * Task
             * @default cutout
             * @enum {string}
             */
            task: "cutout" | "enhance" | "tagging" | "ocr";
            /**
             * Total Images
             * @default 0
             */
            total_images: number;
            /**
             * Total Models
             * @default 0
             */
            total_models: number;
        };
        /** ModelCatalogItem */
        ModelCatalogItem: {
            /** Checksum */
            checksum?: string | null;
            /** Description */
            description: string;
            /** Download Url */
            download_url?: string | null;
            /**
             * Engine
             * @enum {string}
             */
            engine: "rembg" | "realesrgan" | "wdtagger" | "tesseract";
            /** Filename */
            filename?: string | null;
            /** Id */
            id: string;
            /**
             * Included By Default
             * @default false
             */
            included_by_default: boolean;
            /**
             * Install State
             * @enum {string}
             */
            install_state: "not_installed" | "downloading" | "installed" | "failed";
            /**
             * Installable
             * @default true
             */
            installable: boolean;
            /** Installed */
            installed: boolean;
            /** Last Error */
            last_error?: string | null;
            /** Last Used At */
            last_used_at?: string | null;
            /** Local Path */
            local_path?: string | null;
            /** Name */
            name: string;
            /**
             * Runtime Ready
             * @default false
             */
            runtime_ready: boolean;
            /** Size Mb */
            size_mb: number;
            /** Status Note */
            status_note?: string | null;
            /**
             * Task
             * @enum {string}
             */
            task: "cutout" | "enhance" | "tagging" | "ocr";
        };
        /** ModelStatusResponse */
        ModelStatusResponse: {
            /** Id */
            id: string;
            /**
             * Install State
             * @enum {string}
             */
            install_state: "not_installed" | "downloading" | "installed" | "failed";
            /** Installed */
            installed: boolean;
            /** Last Error */
            last_error?: string | null;
            /** Last Used At */
            last_used_at?: string | null;
            /** Local Path */
            local_path?: string | null;
        };
        /** ModelStorageConfig */
        ModelStorageConfig: {
            /** Default Root Dir */
            default_root_dir: string;
            /** Rembg Dir */
            rembg_dir: string;
            /** Root Dir */
            root_dir: string;
            /** Using Custom Root */
            using_custom_root: boolean;
        };
        /** PresetItem */
        PresetItem: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /**
             * Is Builtin
             * @default false
             */
            is_builtin: boolean;
            /**
             * Is Editable
             * @default true
             */
            is_editable: boolean;
            /** Name */
            name: string;
            options: components["schemas"]["ProcessingOptions"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProcessSingleRequest */
        ProcessSingleRequest: {
            /** Image Path */
            image_path: string;
            options: components["schemas"]["ProcessingOptions"];
        };
        /** ProcessingOptions */
        ProcessingOptions: {
            /**
             * Alpha Threshold
             * @default 10
             */
            alpha_threshold: number;
            /**
             * Aspect Ratio
             * @default keep
             */
            aspect_ratio: string;
            /**
             * Background Color
             * @default #FFFFFF
             */
            background_color: string;
            /**
             * Background Mode
             * @default transparent
             * @enum {string}
             */
            background_mode: "transparent" | "solid";
            /**
             * Cutout Engine
             * @default rembg
             * @constant
             */
            cutout_engine: "rembg";
            /**
             * Cutout Model Id
             * @default u2netp
             */
            cutout_model_id: string;
            /**
             * Edge Feather Radius
             * @default 1
             */
            edge_feather_radius: number;
            /**
             * Enhance Engine
             * @default realesrgan
             * @constant
             */
            enhance_engine: "realesrgan";
            /**
             * Enhance Level
             * @default off
             * @enum {string}
             */
            enhance_level: "off" | "2x" | "4x";
            /** Enhance Model */
            enhance_model?: string | null;
            /**
             * Fallback To Api
             * @default false
             */
            fallback_to_api: boolean;
            /**
             * Filename Pattern
             * @default {original_name}_{preset}_{engine}
             */
            filename_pattern: string;
            /** Local Model */
            local_model?: string | null;
            /** Local Quality Preset */
            local_quality_preset?: ("fast" | "balanced" | "hq") | null;
            /**
             * Naming Mode
             * @default pattern
             * @enum {string}
             */
            naming_mode: "keep_original" | "pattern" | "ocr_text";
            /** Naming Regex Find */
            naming_regex_find?: string | null;
            /**
             * Naming Regex Replace
             * @default
             */
            naming_regex_replace: string;
            /**
             * Ocr Language
             * @default eng
             */
            ocr_language: string;
            /**
             * Ocr Max Length
             * @default 48
             */
            ocr_max_length: number;
            /** Output Dir Override */
            output_dir_override?: string | null;
            /**
             * Output Format
             * @default png
             * @enum {string}
             */
            output_format: "png" | "webp" | "jpeg" | "jpg" | "avif";
            /**
             * Padding
             * @default 0
             */
            padding: number;
            /**
             * Preprocess Color Normalization
             * @default false
             */
            preprocess_color_normalization: boolean;
            /**
             * Preprocess Denoise
             * @default false
             */
            preprocess_denoise: boolean;
            /**
             * Preprocess Sharpening
             * @default false
             */
            preprocess_sharpening: boolean;
            /**
             * Preset
             * @default quick_cutout
             */
            preset: string;
            /**
             * Processing Order
             * @default cutout_then_enhance
             */
            processing_order: ("cutout_then_enhance" | "enhance_then_cutout") | null;
            /** Provider Priority */
            provider_priority?: string[];
            /**
             * Quality
             * @default 90
             */
            quality: number;
            /**
             * Remove Background
             * @default true
             */
            remove_background: boolean;
            /** Resize Max Height */
            resize_max_height?: number | null;
            /** Resize Max Width */
            resize_max_width?: number | null;
            /**
             * Resize Mode
             * @default keep
             * @enum {string}
             */
            resize_mode: "keep" | "custom";
            /**
             * Save Alpha Mask
             * @default false
             */
            save_alpha_mask: boolean;
            /**
             * Strip Metadata
             * @default true
             */
            strip_metadata: boolean;
            /**
             * Trim Transparent Bounds
             * @default true
             */
            trim_transparent_bounds: boolean;
            /**
             * White Halo Cleanup
             * @default 35
             */
            white_halo_cleanup: number;
            /**
             * Workflow Mode
             * @default cutout_only
             * @enum {string}
             */
            workflow_mode: "cutout_only" | "enhance_only" | "cutout_enhance";
        };
        /** ProviderApiKey */
        ProviderApiKey: {
            /** Cooldown Until */
            cooldown_until?: string | null;
            /** Daily Limit */
            daily_limit?: number | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Last Error */
            last_error?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Monthly Limit */
            monthly_limit?: number | null;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /** Usage Notes */
            usage_notes?: string | null;
            /**
             * Used Count
             * @default 0
             */
            used_count: number;
        };
        /** ProviderSettingsItem */
        ProviderSettingsItem: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Keys */
            keys?: components["schemas"]["ProviderApiKey"][];
            /** Name */
            name: string;
            /**
             * Priority
             * @default 100
             */
            priority: number;
        };
        /** ProviderSettingsPayload */
        ProviderSettingsPayload: {
            /**
             * Default Quality Preset
             * @default balanced
             * @enum {string}
             */
            default_quality_preset: "fast" | "balanced" | "hq";
            /** Providers */
            providers?: components["schemas"]["ProviderSettingsItem"][];
            /**
             * Use Only Local
             * @default false
             */
            use_only_local: boolean;
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Available */
            available: boolean;
            /** Enabled */
            enabled: boolean;
            /** Healthy */
            healthy: boolean;
            /** Is Local */
            is_local: boolean;
            /** Key Count */
            key_count: number;
            /** Last Error */
            last_error?: string | null;
            /** Name */
            name: string;
            /** Priority */
            priority: number;
        };
        /** RunModelBenchmarkRequest */
        RunModelBenchmarkRequest: {
            /** Model Ids */
            model_ids?: string[] | null;
            /** Sample Dir */
            sample_dir?: string | null;
            /**
             * Task
             * @default cutout
             * @enum {string}
             */
            task: "cutout" | "enhance" | "tagging" | "ocr";
        };
        /** UpdateModelStorageRequest */
        UpdateModelStorageRequest: {
            /**
             * Migration Mode
             * @default move
             * @enum {string}
             */
            migration_mode: "move" | "delete" | "ignore";
            /** Root Dir */
            root_dir?: string | null;
        };
        /** UpdatePresetRequest */
        UpdatePresetRequest: {
            /** Name */
            name?: string | null;
            options?: components["schemas"]["ProcessingOptions"] | null;
        };
        /** UploadItem */
        UploadItem: {
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Source Path */
            source_path?: string | null;
            /**
             * Storage Mode
             * @default uploaded_blob
             * @enum {string}
             */
            storage_mode: "desktop_path" | "uploaded_blob";
            /** Upload Id */
            upload_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchFolderCreateRequest */
        WatchFolderCreateRequest: {
            /**
             * Auto Run
             * @default true
             */
            auto_run: boolean;
            /**
             * Cooldown Ms
             * @default 2000
             */
            cooldown_ms: number;
            /** Failed Folder */
            failed_folder?: string | null;
            /** Input Folder */
            input_folder: string;
            /**
             * Is Enabled
             * @default true
             */
            is_enabled: boolean;
            /**
             * Move Failed Files
             * @default false
             */
            move_failed_files: boolean;
            /**
             * Move Processed Files
             * @default false
             */
            move_processed_files: boolean;
            /** Name */
            name: string;
            /** Output Folder */
            output_folder: string;
            /** Preset Id */
            preset_id: string;
            /** Processed Folder */
            processed_folder?: string | null;
            /**
             * Skip Duplicates
             * @default true
             */
            skip_duplicates: boolean;
        };
        /** WatchFolderItem */
        WatchFolderItem: {
            /**
             * Auto Run
             * @default true
             */
            auto_run: boolean;
            /**
             * Cooldown Ms
             * @default 2000
             */
            cooldown_ms: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Failed Folder */
            failed_folder?: string | null;
            /**
             * Files Processed Count
             * @default 0
             */
            files_processed_count: number;
            /** Id */
            id: string;
            /** Input Folder */
            input_folder: string;
            /**
             * Is Enabled
             * @default true
             */
            is_enabled: boolean;
            /** Last Activity At */
            last_activity_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /** Last Processed At */
            last_processed_at?: string | null;
            /**
             * Move Failed Files
             * @default false
             */
            move_failed_files: boolean;
            /**
             * Move Processed Files
             * @default false
             */
            move_processed_files: boolean;
            /** Name */
            name: string;
            /** Output Folder */
            output_folder: string;
            /** Preset Id */
            preset_id: string;
            /**
             * Preset Missing
             * @default false
             */
            preset_missing: boolean;
            /** Processed Folder */
            processed_folder?: string | null;
            /**
             * Skip Duplicates
             * @default true
             */
            skip_duplicates: boolean;
            /**
             * Status
             * @default idle
             * @enum {string}
             */
            status: "idle" | "watching" | "paused" | "error" | "unsupported";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WatchFolderUpdateRequest */
        WatchFolderUpdateRequest: {
            /** Auto Run */
            auto_run?: boolean | null;
            /** Cooldown Ms */
            cooldown_ms?: number | null;
            /** Failed Folder */
            failed_folder?: string | null;
            /** Input Folder */
            input_folder?: string | null;
            /** Is Enabled */
            is_enabled?: boolean | null;
            /** Move Failed Files */
            move_failed_files?: boolean | null;
            /** Move Processed Files */
            move_processed_files?: boolean | null;
            /** Name */
            name?: string | null;
            /** Output Folder */
            output_folder?: string | null;
            /** Preset Id */
            preset_id?: string | null;
            /** Processed Folder */
            processed_folder?: string | null;
            /** Skip Duplicates */
            skip_duplicates?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    open_output_folder_fs_open_output_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    reveal_file_fs_reveal_post: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_history_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_history_history__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_job_jobs_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBatchJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_output_jobs_download_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_local_paths_jobs_ingest_paths_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestPathsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_single_jobs_single_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessSingleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_files_jobs_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_files_jobs_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_job_zip_jobs__job_id__zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_model_benchmark_models_benchmark_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunModelBenchmarkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelBenchmarkStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_benchmark_status_models_benchmark_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelBenchmarkStatus"];
                };
            };
        };
    };
    list_model_catalog_models_catalog_get: {
        parameters: {
            query?: {
                task?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_storage_config_models_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStorageConfig"];
                };
            };
        };
    };
    update_model_storage_config_models_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateModelStorageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStorageConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_model_catalog_models_refresh_post: {
        parameters: {
            query?: {
                task?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_model_models__model_id__install_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_status_models__model_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetItem"][];
                };
            };
        };
    };
    create_preset_presets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePresetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_preset_presets__preset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preset_presets__preset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePresetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_settings_providers_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSettingsPayload"];
                };
            };
        };
    };
    save_provider_settings_providers_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderSettingsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSettingsPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_status_providers_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"][];
                };
            };
        };
    };
    test_provider_providers_test__provider_name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watch_folders_watch_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchFolderItem"][];
                };
            };
        };
    };
    create_watch_folder_watch_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchFolderCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchFolderItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watch_folder_watch_folders__watch_folder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watch_folder_watch_folders__watch_folder_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchFolderUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchFolderItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_watch_folder_watch_folders__watch_folder_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchFolderItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_watch_folder_watch_folders__watch_folder_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchFolderItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watch_folder_status_watch_folders__watch_folder_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchFolderItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
