import type { PresetItem, ProcessingOptions } from "@/types";

function options(preset: string, overrides: Partial<ProcessingOptions>): ProcessingOptions {
  return {
    workflow_mode: "cutout_only",
    processing_order: "cutout_then_enhance",
    preset,
    provider_priority: ["rembg_local"],
    remove_background: true,
    cutout_engine: "rembg",
    cutout_model_id: "u2netp",
    local_model: "u2netp",
    local_quality_preset: "balanced",
    enhance_level: "off",
    enhance_engine: "realesrgan",
    enhance_model: null,
    preprocess_denoise: false,
    preprocess_color_normalization: false,
    preprocess_sharpening: false,
    fallback_to_api: false,
    trim_transparent_bounds: true,
    padding: 0,
    resize_mode: "keep",
    resize_max_width: null,
    resize_max_height: null,
    aspect_ratio: "keep",
    background_mode: "transparent",
    background_color: "#ffffff",
    output_dir_override: null,
    output_format: "png",
    quality: 90,
    strip_metadata: true,
    naming_mode: "pattern",
    filename_pattern: "{original_name}_{preset}_{engine}",
    naming_regex_find: "",
    naming_regex_replace: "",
    ocr_language: "eng",
    ocr_max_length: 48,
    alpha_threshold: 10,
    edge_feather_radius: 1,
    white_halo_cleanup: 35,
    save_alpha_mask: false,
    ...overrides,
  };
}

const now = new Date().toISOString();

export const FALLBACK_PRESETS: PresetItem[] = [
  {
    id: "quick_cutout",
    name: "Quick Cutout",
    is_builtin: true,
    is_editable: false,
    created_at: now,
    updated_at: now,
    options: options("quick_cutout", {
      cutout_model_id: "birefnet-general-lite",
      local_model: "birefnet-general-lite",
      local_quality_preset: "balanced",
      output_format: "png",
      quality: 95,
    }),
  },
  {
    id: "product_image",
    name: "Product Image",
    is_builtin: true,
    is_editable: false,
    created_at: now,
    updated_at: now,
    options: options("product_image", {
      cutout_model_id: "birefnet-general",
      local_model: "birefnet-general",
      local_quality_preset: "hq",
      padding: 24,
      output_format: "webp",
      quality: 90,
    }),
  },
  {
    id: "portrait",
    name: "Portrait",
    is_builtin: true,
    is_editable: false,
    created_at: now,
    updated_at: now,
    options: options("portrait", {
      cutout_model_id: "birefnet-general",
      local_model: "birefnet-general",
      local_quality_preset: "hq",
      quality: 100,
    }),
  },
  {
    id: "anime_art",
    name: "Anime / Art",
    is_builtin: true,
    is_editable: false,
    created_at: now,
    updated_at: now,
    options: options("anime_art", {
      cutout_model_id: "u2netp",
      local_model: "u2netp",
      local_quality_preset: "fast",
      quality: 100,
    }),
  },
  {
    id: "convert_only",
    name: "Convert Only",
    is_builtin: true,
    is_editable: false,
    created_at: now,
    updated_at: now,
    options: options("convert_only", {
      remove_background: false,
      trim_transparent_bounds: false,
      quality: 92,
    }),
  },
  {
    id: "remove_trim_webp",
    name: "Remove + Trim + WebP",
    is_builtin: true,
    is_editable: false,
    created_at: now,
    updated_at: now,
    options: options("remove_trim_webp", {
      cutout_model_id: "birefnet-general-lite",
      local_model: "birefnet-general-lite",
      output_format: "webp",
      quality: 86,
    }),
  },
];
